package pl.kamil_dywan.gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Function;

public class PaginationTableGui extends JPanel {

    private JPanel mainPanel;

    private JTable table;
    private DefaultTableModel tableModel;
    private JScrollPane tableScroll;

    private JToolBar pagination;
    private JButton previousButton;
    private JToolBar paginationNumbers;
    private JButton nextButton;

    private JToolBar paginationSize;
    private JComboBox<Integer> paginationSizeSelector;
    private JLabel rowsInfo;

    private final String[] tableHeaders;
    private final Integer[] columnsWidths;

    private final BiFunction<Integer, Integer, PaginationTableData> loadData;
    private final Function<Object, Object[]> convertToRow;

    private int offset = 0;
    private int pageSize = 10;
    private int totalNumberOfRows = 0;

    public PaginationTableGui(
            String[] tableHeaders,
            Integer[] columnsWidths,
            BiFunction<Integer, Integer, PaginationTableData> loadData,
            Function<Object, Object[]> convertToRow
    ) {
        this.tableHeaders = tableHeaders;
        this.columnsWidths = columnsWidths;
        this.loadData = loadData;
        this.convertToRow = convertToRow;

        $$$setupUI$$$();

        previousButton.addActionListener(e -> handlePreviousButton());

        nextButton.addActionListener(e -> handleNextButton());

        paginationSizeSelector.addActionListener(e -> handlePageSizeSelectorChange());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setAlignmentX(0.0f);
        mainPanel.setAlignmentY(0.0f);
        mainPanel.setFocusable(false);
        mainPanel.setMinimumSize(new Dimension(600, 414));
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new Dimension(800, 600));
        mainPanel.setRequestFocusEnabled(true);
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), "            ", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tableScroll = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.gridheight = 2;
        gbc.weightx = 10.0;
        gbc.weighty = 8.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        mainPanel.add(tableScroll, gbc);
        table.setEnabled(false);
        table.setFocusable(false);
        table.setRowHeight(33);
        tableScroll.setViewportView(table);
        pagination = new JToolBar();
        pagination.setBackground(new Color(-1114625));
        pagination.setFloatable(false);
        pagination.setForeground(new Color(-1));
        pagination.setOpaque(false);
        pagination.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 10.0;
        gbc.weighty = 1.0;
        mainPanel.add(pagination, gbc);
        pagination.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        pagination.add(toolBar$Separator1);
        final JToolBar.Separator toolBar$Separator2 = new JToolBar.Separator();
        pagination.add(toolBar$Separator2);
        previousButton = new JButton();
        previousButton.setText("<");
        pagination.add(previousButton);
        final JToolBar.Separator toolBar$Separator3 = new JToolBar.Separator();
        pagination.add(toolBar$Separator3);
        paginationNumbers = new JToolBar();
        paginationNumbers.setFloatable(false);
        paginationNumbers.setForeground(new Color(-1));
        paginationNumbers.setOpaque(false);
        pagination.add(paginationNumbers);
        final JToolBar.Separator toolBar$Separator4 = new JToolBar.Separator();
        pagination.add(toolBar$Separator4);
        nextButton = new JButton();
        nextButton.setText(">");
        pagination.add(nextButton);
        rowsInfo = new JLabel();
        rowsInfo.setHorizontalAlignment(11);
        rowsInfo.setText("Wiersze 0 - 0 z 0");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 50, 0, 0);
        mainPanel.add(rowsInfo, gbc);
        paginationSize = new JToolBar();
        paginationSize.setFloatable(false);
        paginationSize.setOpaque(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(paginationSize, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Liczba wierszy:");
        paginationSize.add(label1);
        final JToolBar.Separator toolBar$Separator5 = new JToolBar.Separator();
        paginationSize.add(toolBar$Separator5);
        paginationSizeSelector = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("10");
        defaultComboBoxModel1.addElement("25");
        defaultComboBoxModel1.addElement("50");
        defaultComboBoxModel1.addElement("100");
        paginationSizeSelector.setModel(defaultComboBoxModel1);
        paginationSize.add(paginationSizeSelector);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public record PaginationTableData(
            List<?> data,
            int totalNumberOfRows
    ) {
    }

    private void handlePreviousButton() {

        if (offset == 0) {
            return;
        }

        offset -= pageSize;

        handleLoadTableExceptions();
    }

    private void handleNextButton() {

        if (offset + pageSize >= totalNumberOfRows) {
            return;
        }

        offset += pageSize;

        handleLoadTableExceptions();
    }

    private void handlePageSizeSelectorChange() {

        pageSize = getCurrentPageSize();

        handleLoadTableExceptions();
    }

    public void handleLoadTableExceptions() {

        mainPanel.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            loadTable();
        } catch (IllegalAccessException e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(mainPanel, "Nie udało się załadować tabeli", "Błąd", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadTable() throws IllegalAccessException {

        new Thread(() -> {

            PaginationTableData gotRawTableData = loadData.apply(offset, pageSize);

            if (gotRawTableData == null) {
                return;
            }

            SwingUtilities.invokeLater(() -> {

                tableModel.setNumRows(0);

                for (Object gotDataRawRow : gotRawTableData.data) {

                    Object[] newRow = convertToRow.apply(gotDataRawRow);

                    tableModel.addRow(newRow);
                }

                totalNumberOfRows = gotRawTableData.totalNumberOfRows();
                rowsInfo.setText("Wiersze " + (offset + 1) + " - " + (offset + tableModel.getRowCount()) + " z " + totalNumberOfRows);

                handleLoadPaginationNumbersButtons();

                mainPanel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            });

        }).start();
    }

    private void handleLoadPaginationNumbersButtons() {

        paginationNumbers.removeAll();

        int numberOfPages = getNumberOfPages();
        int actualPage = getActualPage();

        int numberOfButtons = Math.min(numberOfPages, 4);
        int actualButtonIndex = actualPage % 4;

        int minPageButton = actualPage - actualButtonIndex;
        int minOffsetButton = minPageButton * offset;

        for (int i = 0; i < numberOfButtons; i++) {

            int buttonPage = minPageButton + i;

            JButton pageButton = new JButton(String.valueOf(buttonPage + 1));

            if (i == actualButtonIndex) {

                pageButton.setBackground(Color.GRAY);
            }

            int finalButtonPageOffset = minOffsetButton + i;

            pageButton.addActionListener(e -> {

                offset += finalButtonPageOffset;

                handleLoadTableExceptions();
            });

            paginationNumbers.add(pageButton);
            paginationNumbers.repaint();
        }
    }

    private int getActualPage() {

        return offset / pageSize;
    }

    private int getNumberOfPages() {

        int numberOfPages = 1;

        if (totalNumberOfRows > pageSize) {

            numberOfPages = totalNumberOfRows / pageSize;
        }

        return numberOfPages;
    }

    private Integer getCurrentPageSize() {

        String currentSelectedPageSize = (String) paginationSizeSelector.getSelectedItem();

        return Integer.valueOf(currentSelectedPageSize);
    }

    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        DefaultTableCellRenderer cellsCenterRenderer = new DefaultTableCellRenderer();

        cellsCenterRenderer.setHorizontalAlignment(JLabel.CENTER);

        tableModel = new DefaultTableModel(tableHeaders, 0);

        table = new JTable(tableModel);

        for (int i = 0; i < tableHeaders.length; i++) {

            Integer columnWidth = columnsWidths[i];

            TableColumn column = table.getColumnModel().getColumn(i);

            column.setCellRenderer(cellsCenterRenderer);
//            column.setMaxWidth(columnWidth);
        }
    }
}
